### ISSUE TITLE
Fix Compile issue when PlayerShip.cpp includes SoundRes.cpp

### ISSUE THREAD

**Issue by Caishangqi** [Caishangqi/Eurekiel#1]
> ## TODO
> 
> 
> 
> The compile error when `#include` the `SoundRes.cpp` in `PlayerShip.cpp` 

 _Originally posted by @Caishangqi in [d4adb9d](https://github.com/Caishangqi/Eurekiel/commit/d4adb9d72edac33b789acca324600c90f7e3258b#r147761779)_

**Comment by barroit** [comment]
You want to include a source file in another source file? Seriously, you're a moron. Is your brain malfunctioning? Do I need to explain some basic, stupid concepts to you, like what is happening under the hood? I hope you never do anything this fucking crap again.

**Comment by barroit** [comment]
And, this is NOT a compilation error. It's a linkage error, you dumb idiot.

**Comment by Caishangqi** [comment]
Fixed By Squirrel
